# Generated by Django 3.0.5 on 2020-09-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=20, null=True)),
                ('A1', models.CharField(blank=True, max_length=1, null=True)),
                ('A2', models.CharField(blank=True, max_length=1, null=True)),
                ('A3', models.CharField(blank=True, max_length=1, null=True)),
                ('A4', models.CharField(blank=True, max_length=1, null=True)),
                ('A5', models.CharField(blank=True, max_length=1, null=True)),
                ('A6', models.CharField(blank=True, max_length=1, null=True)),
                ('A7', models.CharField(blank=True, max_length=1, null=True)),
                ('A8', models.CharField(blank=True, max_length=1, null=True)),
                ('A9', models.CharField(blank=True, max_length=1, null=True)),
                ('A10', models.CharField(blank=True, max_length=1, null=True)),
                ('A11', models.CharField(blank=True, max_length=1, null=True)),
                ('A12', models.CharField(blank=True, max_length=1, null=True)),
                ('A13', models.CharField(blank=True, max_length=1, null=True)),
                ('A14', models.CharField(blank=True, max_length=1, null=True)),
                ('A15', models.CharField(blank=True, max_length=1, null=True)),
                ('A16', models.CharField(blank=True, max_length=1, null=True)),
                ('A17', models.CharField(blank=True, max_length=1, null=True)),
                ('A18', models.CharField(blank=True, max_length=1, null=True)),
                ('A19', models.CharField(blank=True, max_length=1, null=True)),
                ('A20', models.CharField(blank=True, max_length=1, null=True)),
                ('A21', models.CharField(blank=True, max_length=1, null=True)),
                ('A22', models.CharField(blank=True, max_length=1, null=True)),
                ('A23', models.CharField(blank=True, max_length=1, null=True)),
                ('A24', models.CharField(blank=True, max_length=1, null=True)),
                ('A25', models.CharField(blank=True, max_length=1, null=True)),
                ('A26', models.CharField(blank=True, max_length=1, null=True)),
                ('A27', models.CharField(blank=True, max_length=1, null=True)),
                ('A28', models.CharField(blank=True, max_length=1, null=True)),
                ('A29', models.CharField(blank=True, max_length=1, null=True)),
                ('A30', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=500)),
                ('teamName', models.CharField(max_length=200)),
                ('emailT1', models.EmailField(max_length=254)),
                ('emailT2', models.EmailField(max_length=254)),
                ('contactT1', models.CharField(max_length=20)),
                ('contactT2', models.CharField(max_length=20)),
                ('nameT1', models.CharField(max_length=50)),
                ('nameT2', models.CharField(max_length=50)),
                ('teamId', models.CharField(max_length=20)),
                ('nameTeacher', models.CharField(max_length=20)),
                ('emailTeacher', models.EmailField(max_length=254)),
                ('contactTeacher', models.CharField(max_length=20)),
                ('schoolAddress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('A', models.CharField(max_length=1000)),
                ('B', models.CharField(max_length=1000)),
                ('C', models.CharField(max_length=1000)),
                ('D', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQuiz',
            fields=[
                ('qId', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('A', models.CharField(max_length=1000)),
                ('B', models.CharField(max_length=1000)),
                ('C', models.CharField(max_length=1000)),
                ('D', models.CharField(max_length=1000)),
            ],
        ),
    ]
